apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-postgres-todo
  namespace: development
  labels:
    app: postgres-todo
data: 
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: rahasia
  POSTGRES_DB: belajar
